spring.application.name=lawny-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/lawny
spring.datasource.username=lawny_user
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update